### ISSUE TITLE
Support "rel" attribute

### ISSUE THREAD

**Issue by nwhittaker** [johnotander/ember-linkify#18]
A [security vulnerability](https://medium.com/@jitbit/target-blank-the-most-underestimated-vulnerability-ever-96e328301f4c) exists in the inherent mechanics of opening links with `target="_blank"`. In short, the _opened_ window can cause its _opener_ to navigate to a malicious site via the new window's `window.opener.location` object. Sites with user-generated content may be especially susceptible.

The [proposed fix](https://github.com/whatwg/html/pull/290) is to specify a special `rel` attribute. Browser support is [currently poor](http://caniuse.com/#feat=rel-noopener), but it might be good to at least remove `ember-linkify` as a barrier to specifying this attribute in anchor tag mark-up. Maybe add `rel` as a supported option?

Further description and bug tracking issues at https://mathiasbynens.github.io/rel-noopener/.

**Comment by nwhittaker** [comment]
If agreed, I'm happy to work on a PR for this...

**Comment by johnotander** [comment]
That would be great, happy to accept a PR. Thank you!
