### ISSUE TITLE
Don't include punctuation in link

### ISSUE THREAD

**Issue by simenheg** [johnotander/ember-linkify#22]
When a URL appears at the end of a punctuated sentence the punctuation mark is included in the link, which is almost always not what one wants.

For instance, the text `Check out this link: http://foo.org.` becomes `Check out this link: <a href="http://foo.org.">http://foo.org.</a>` instead of the expected `Check out this link: <a href="http://foo.org">http://foo.org</a>.`.

**Comment by kamikaz1k** [comment]
I'm not sure when this was fixed but as of v3.0.0 it seems to work as you are expecting it to.
