### ISSUE TITLE
Trailing newlines are stripped

### ISSUE THREAD

**Issue by nwhittaker** [johnotander/ember-linkify#23]
A newline immediately following a link gets stripped.
### Steps to reproduce

Run a link with a trailing newlines through `ember-linkify`.
### Observed behavior

```
http://example.com
next line
```

becomes

```
<a href="http://example.com">http://example.com</a> next line
```
### Expected behavior

```
http://example.com
next line
```

becomes

```
<a href="http://example.com">http://example.com</a>
next line
```

**Comment by kamikaz1k** [comment]
Not sure if someone else wants to weigh in on this, but I think that is just normal handlebars/HTML behaviour. Newline characters are ignored, unless you use some CSS.

Reference: https://groups.google.com/forum/#!topic/meteor-talk/bCiaQi4Zrgc
As that thread suggests, you could try the CSS rule `white-space: pre` inside of a div to preserve line breaks.

**Comment by nwhittaker** [comment]
@kamikaz1k the newline character is stripped in the source, so I'd expect you'd still see the observed behavior despite any `pre` styling.

**Comment by kamikaz1k** [comment]
@nwhittaker ah, yes the regex+trim does do that, my mistake. I was testing the fix on my PR where it was working. In the PR I updated the url-regex to ignore the whitespace before and after the url so it should fix this issue too (if you use `pre`). 

The PR has been submitted, you can have a look here if you like: https://github.com/johnotander/ember-linkify/pull/27

**Comment by kamikaz1k** [comment]
Version 3.0.0 preserves whitespace
